### ISSUE TITLE
Decommission: snowdrop.me

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/team#1042]
## TODO

Decommission: snowdrop.me

- [x] Don't renew anymore snowdrop.me certificates with Let's encrypt
- [x] Delete the certificate and issuer YAML on ax51-nvme machine
- [x] Remove the snowdrop.me DNS entries from GoDaddy
- [ ] Terminate snowdrop.me DNS name contract (Godaddy)

FYI: @jacobdotcosta

**Comment by cmoulliard** [comment]
DNS entries removed:
```
A	@	195.201.87.126
A	generator	195.201.87.126
A	start	195.201.87.126
A	www	195.201.87.126
CNAME - beta - snowdrop-site-angular-snowdrop-site.195.201.87.126.nip.io.
CNAME - ftp | snowdrop.me.
```

**Comment by jacobdotcosta** [comment]
Change the groupid in the Snowdrop Narayana Spring Boot Starter to `dev.snowdrop`: snowdrop/narayana-spring-boot#111
