### ISSUE TITLE
Decommission: snowdrop.dev

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/team#1043]
## TODO

Decommission: snowdrop.dev web sites

- [x] Stop and remove the snowdrop web sites: www, generator and start.swowdrop.dev
- [x] Archive the github project: 
- [x]  Don't renew anymore www|start|generator.snowdrop.dev certificates with Let's encrypt
- [x]  Delete the certificate and issuer YAML on ax51-nvme machine
- [x]  Remove the www|start|generator.snowdrop.dev DNS entries from GoDaddy
