### ISSUE TITLE
Release 2.7.13.CR

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#1055]
CR release
- [x] Update the build configuration
- [x] Release project
- [x] Update GAV versions according to the build result
- [x] Release examples
- [x] Update and transition advisory
- [x] Promote release to candidates
- [x] Check snyk tests

**Comment by jacobdotcosta** [comment]
There's an error promoting the files to candidates. Looking for support.
