### ISSUE TITLE
Release 2.7.15 ER

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#1062]
- [x] Create JIRA ticket
- [x] Get dependencies from SB project
- [x] Align examples
  - [x] SB Version
  - [x] Upstream lib versions
- [x] Release examples
- [x] Update `artifact-list` file
- [x] Errata Advisory

**Comment by jacobdotcosta** [comment]
Error tagging the `dev.snowdrop.example:crud:jar:2.7.15-1-redhat` example:

```
The following artifacts could not be resolved: io.fabric8:openshift-client:jar:5.12.4.redhat-00002, io.fabric8:openshift-model:jar:5.12.4.redhat-00002, io.fabric8:openshift-model-clusterautoscaling:jar:5.12.4.redhat-00002, io.fabric8:openshift-model-operator:jar:5.12.4.redhat-00002, io.fabric8:openshift-model-operatorhub:jar:5.12.4.redhat-00002, io.fabric8:openshift-model-machine:jar:5.12.4.redhat-00002, io.fabric8:openshift-model-whereabouts:jar:5.12.4.redhat-00002, io.fabric8:openshift-model-monitoring:jar:5.12.4.redhat-00002, io.fabric8:openshift-model-storageversionmigrator:jar:5.12.4.redhat-00002, io.fabric8:openshift-model-tuned:jar:5.12.4.redhat-00002, io.fabric8:openshift-model-console:jar:5.12.4.redhat-00002, io.fabric8:openshift-model-machineconfig:jar:5.12.4.redhat-00002, io.fabric8:openshift-model-miscellaneous:jar:5.12.4.redhat-00002, io.fabric8:openshift-model-hive:jar:5.12.4.redhat-00002, io.fabric8:openshift-model-installer:jar:5.12.4.redhat-00002: Could not transfer artifact io.fabric8:openshift-client:jar:5.12.4.redhat-00002 from/to indy (http://indy.psi.redhat.com/api/group/static/): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]"
, "[ERROR] "
, "[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch."
, "[ERROR] Re-run Maven using the -X switch to enable full debug logging.", "[ERROR] ", "[ERROR] For more information about the errors and possible solutions, please read the following articles:", "[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException"]
```

**Comment by jacobdotcosta** [comment]
The problem was insufficient disk space.
