### ISSUE TITLE
SB 2.7.17 ER

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#1081]
- [x] Create the release folder
- [x] Update gav-versions.yaml with Spring Boot
- [x] Align Examples with Upstream (All releases)
- [ ] ~Align the Narayana Spring Boot Starter~
- [ ] ~Release the Narayana Spring Boot Starter~
- [ ] Productization (Full release)
  - [x] Update the build configuration
  - [ ] Test the build configuration locally
  - [x] Update the CPaaS information
    - [x] Remove the advisory_map file
    - [x] Product file
    - [x] Release file (the errata advisory creation)
    - [x] Update CPaaS configuration
    - [x] Create MR
  - [x] Launch the build
- [ ] Release Validations
  - [x] Check the repository duplicate artifact list report
  - [ ] Check PSSC scan results (Full releases)
- [x] Update the gav-versions file (Full releases)
- [x] Release Examples 
- [ ] Verify the boosters/examples
- [x] Generate the artifact-list file
- [x] Create the Errata advisory
- [x] Inform QE

**Comment by jacobdotcosta** [comment]
Align Examples with Upstream:
* snowdrop/istio-distributed-tracing-example#86
* snowdrop/health-check-example#113
* snowdrop/crud-example#146
* snowdrop/configmap-example#137

**Comment by jacobdotcosta** [comment]
Created the advisory beforehand.

**Comment by jacobdotcosta** [comment]
Fixed error on the `artifact-list.txt` reported by QE.
