### ISSUE TITLE
Plan automating parts of the the productization process (EPIC)

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#12]
- [ ] Gathering versions from upstream and upstream starter
 - [ ] Gathering productized versions related to the upstream versions
 - [ ] Fill the `pom.xml` and the `build-config` files with versions selected, gathering information from a unified source without having to manually input it.
 - [ ] Allow launching jenkins run-pfg job from the command line
