### ISSUE TITLE
R&D: Study Ansible Molecule

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/team#143]
## TODO

- [x] Study Ansible Molecule
- [x] Evaluate how to use molecule to test kind, jcliff
- [ ] Check how to define asserts
- [ ] Play with Ansible module concept - https://opensource.com/article/19/3/developing-ansible-modules
