### ISSUE TITLE
Investigate if we could design a knative adapter for spring cloud function

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/team#180]
## TODO

- [x] Investigate if we could design a knative adapter for spring cloud function
- [x] Review openwhisk vs knative
- [ ] Check how we could package/Deploy a function on knative
