### ISSUE TITLE
Improve JIRA Java Prod client

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/team#189]
## TODO

- [x] Adopt the release.yaml as the contract definition of a new release
- [x] Polish, improve the code
- [x] Link the CVEs if some are defined within the release.yaml file
- [x] Externalize the title to be used to create a JIRA stakeholder issue as this text is too long
