### ISSUE TITLE
Delete "springboot-eng-staff" mailing list

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/team#44]
## TODO

- [x] Delete `springboot-eng-staff` mailman - [mailing list](https://post-office.corp.redhat.com/mailman/listinfo/springboot-eng-staff)
- [x] Delete `rh-spring-engineering` mailman - [mailing list](https://post-office.corp.redhat.com/mailman/listinfo/rh-spring-engineering)
- [x] Update `SpringBoot Team Info` Google Document
- [x] Communicate to the team what we will use now as forum/email:
  - `snowdrop-team@redhat.com` for all prod/releasing/cve/cases discussions - [forum](https://groups.google.com/a/redhat.com/forum/#!topic/snowdrop-team)
  - ` cmoullia-staff@redhat.com` for team only - [forum](https://groups.google.com/a/redhat.com/forum/#!topic/cmoullia-staff)
