### ISSUE TITLE
Create project for the Snowdrop Buildpacks

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/team#470]
## TODO

- [x] Create Github repository to host the Snowdrop Buildpacks
- [x] Refactor the project to build spring boot projects
- [ ] Support fat jar or source projects

**Comment by BarDweller** [comment]
Closing this, the project does exist, and fat-jar/source support is a function of the buildpack builder image being used, not the library. 

We can track additional requirements for the library via it's own github. https://github.com/snowdrop/java-buildpack-client
