### ISSUE TITLE
Productization / Adapt productization to PNC 2 (using 2.3)

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#57]
Using the new snowdrop release 2.3, test and adapt the productization to the new PNC 2.

- [x] Install and configure the `bacon` client to connect to PNC Dev and build from there
- [x] Create the spring-boot structure in the new PNC (done manually but might be done using `bacon`)
   - [x] SCM for all builds
   - [x] Product
   - [x] Project
 - [x] Update the `spring-boot-bom` versions in the `pom.xml` file
 - [x] Update the `spring-boot-bom` versions in the `build-config.yaml` file
 - [x] Import the build configuration using `bacon`
 - [x] Launch build using `bacon`
 - [x] Download the repository build using `bacon`
 - ~[ ] Check which other projects should be updated for a new minor version~
   - ~[ ] `spring-boot-bom`~
      - ~[ ] `rename the BOM repo`~
   - ~[ ] `product-files-generator`~
      - ~[ ] `enable flattening plugin in the PNC`~
   - ~[ ] `snowdrop-automation-client`~
- [x] Update Jenkins jobs to use the new functionality
   - [x] ~`build-pfg` ~
   - [x] `run-pfg`

**Comment by jacobdotcosta** [comment]
- [ ] Adding dependencies is failing - [Adding a Build Config dependency doesn't seem to do anything](https://projects.engineering.redhat.com/projects/NCL/issues/NCL-5793)
- [ ] Configuring the PIG client to connect to PNC Dev and build from there

**Comment by jacobdotcosta** [comment]
Created a document with the tests performed and the result.

**Comment by jacobdotcosta** [comment]
Created the `build-config` for 2.3.2 using `bacon`:

```bash
$ bacon pig configure spring-boot-2.3-PNC2 --skipBranchCheck --verbose
```

**Comment by jacobdotcosta** [comment]
Downloading the repository build using `bacon` failed - https://projects.engineering.redhat.com/browse/NCLSUP-100

**Comment by jacobdotcosta** [comment]
Launched the build for version 2.3.2 using `bacon`:
```bash
$ bacon pig build spring-boot-2.3-PNC2/ --tempBuild
```
