### ISSUE TITLE
Release 2.8 still blocked due to lack of feedback or 3rd party release delayed from projects

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#682]
- [ ] EAP 7.4.3 that should be CR on February 2nd.
- [ ] DG 8.3.0 that should be CR on February 2nd.
- [x] AMQP which haven't replied to our information request ticket.
