### ISSUE TITLE
Development plan for the snowdrop-bot 

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#7]
Short term goals:

- [x] Add JIRA support to the bot: [snowdrop-bot 53](https://github.com/snowdrop-bot/snowdrop-bot/issues/53)
- [x] Make the Issue entity more generic to support information from other sources such as JIRA: [snowdrop-bot 55](https://github.com/snowdrop-bot/snowdrop-bot/issues/55)
- [ ] Replace the git/jira client library with jboss-set/aphrodite: [snowdrop-bot 85](https://github.com/snowdrop-bot/snowdrop-bot/issues/85)
- [ ] Migrate the weekly report to a discussion: [snowdrop-bot 84](https://github.com/snowdrop-bot/snowdrop-bot/issues/84)
- [x] Generate Jira CVE report: [snowdrop-bot 59](https://github.com/snowdrop-bot/snowdrop-bot/issues/59)
- [x] Deploy snowdrop-bot on production - [snowdrop-bot/snowdrop-bot issue-155](https://github.com/snowdrop/k8s-infra/issues/155)

Not urgent task: 
- [ ] Build quarkus application to manage requests and vm and app inventory - [snowdrop-bot/snowdrop-bot issue-157](https://github.com/snowdrop/k8s-infra/issues/157)

**Comment by cmoulliard** [comment]
I think that we did all the job defined within this ticket and by consequence it can be closed @jacobdotcosta
