### ISSUE TITLE
Remove duplicates on DR1

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#700]
DR1 had duplicates on `org.apache:apache` that must be removed.

- [ ] org.apache.qpid:proton-j-parent
    - [ ] 0.33.8.redhat-00001
    - [ ] 0.33.9.redhat-00001
- [ ] org.apache.qpid:proton-j
    - [ ] 0.33.8.redhat-00001
    - [ ] 0.33.9.redhat-00001
- [ ] org.apache:apache:
    - [x] 18.0.0.redhat-1
    - [ ] 21.0.0.redhat-00001
    - [ ] 23.0.0.redhat-00001
    - [ ] 23.0.0.redhat-00004
```

**Comment by jacobdotcosta** [comment]
18.0.0.redhat-1 removed

**Comment by jacobdotcosta** [comment]
Fixed with Vert.x version 4.2.5 and AMQP 2.5.5
