### ISSUE TITLE
SB 2.5.10.CR

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#792]
-  [x] Release Upstream Final
-  [x] Update Examples
-  [x] Quick Test examples
-  [x] Productize BOM CR 
   -  [x] Update build configuration
   -  [x] Update CPaaS
   -  [x] Launch build
   -  [x] Test release
   -  [x] Generate advisory
-  [x] Release examples
-  [x] Inform QA
