### ISSUE TITLE
2.5.12 ER release

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#798]
- [x] Update the BOM - Align upstream BOM
- [x] Check test results
- [x] Create JIRA release Ticket
- [x] Update the upstream project
- [x] Upstream Release
  - [x] Release Upstream BOM
  - [x] Update examples
  - [x] Test examples
- [x] Productize BOM
  - [x] Update the build configuration
  - [x] Update the CPaaS information
  - [x] Create MR
  - [x] Launch the build
  - [x] Test the release
- [x] Release examples
- [x] Inform QE

**Comment by jacobdotcosta** [comment]
[2.5.12.Beta1](https://github.com/snowdrop/spring-boot-bom/releases/tag/2.5.12.Beta1)

**Comment by jacobdotcosta** [comment]
### cache-example

pom.xml (upstream) > 
```xml 
PARENT: 2.5.12.Beta1
SPRING BOOT VERSION: 2.5.12
```

### circuit-breaker-example:
 
pom.xml (upstream) > 
```xml 
PARENT: 2.5.12.Beta1
SPRING BOOT VERSION: 2.5.12
```
 
### configmap-example:
 
pom.xml (upstream) > 
```xml 
PARENT: 2.5.12.Beta1
SPRING BOOT VERSION: 2.5.12
```
 
### crud-example:
 
pom.xml (upstream) > 
```xml 
PARENT: 2.5.12.Beta1
SPRING BOOT VERSION: 2.5.12
```
 
### health-check-example:
 
pom.xml (upstream) > 
```xml 
PARENT: 2.5.12.Beta1
SPRING BOOT VERSION: 2.5.12
```
 
### istio-distributed-tracing-example:
 
pom.xml (upstream) > 
```xml 
PARENT: 2.5.12.Beta1
SPRING BOOT VERSION: 
```
 
### messaging-work-queue-example:
 
pom.xml (upstream) > 
```xml 
PARENT: 2.5.12.Beta1
SPRING BOOT VERSION: 
```
 
### rest-http-example:
 
pom.xml (upstream) > 
```xml 
PARENT: 2.5.12.Beta1
SPRING BOOT VERSION: 2.5.12
```
 
### secured-example:
 
pom.xml (upstream) > 
```xml 
PARENT: 2.5.12.Beta1
SPRING BOOT VERSION: 2.5.12
```

**Comment by jacobdotcosta** [comment]
Build comparator between 2.5.10.CR1 and 2.5.12.ER1 only shows changes on the `org.springframework.boot` and `dev.snowdrop:snowdrop-dependencies` version to the new `2.5.12` and `2.5.12.Beta1`

**Comment by jacobdotcosta** [comment]
The marete tests only reported the apache duplicates that already existed in `2.5.10.CR1`.
