### ISSUE TITLE
2.5.12.Final CR Release

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#801]
- [x] Update the upstream project
- [x] Upstream Release
  - [x] Release Upstream BOM
  - [x] Update examples
  - [x] Test examples
- [x] Productize BOM
  - [x] Update the build configuration
  - [x] Update the CPaaS information
  - [x] Create MR
  - [x] Launch the build
  - [x] Test the release
- [x] Release examples
- [x] Stage release
- [x] Inform QE
