### ISSUE TITLE
Improve weekly report generated

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/team#82]
## TODO

Improve weekly report generated to 
- [x] Display the full user name and not our github acronym: cmoulliard -> Charles Moulliard within the report - https://github.com/snowdrop-bot/snowdrop-bot/issues/71
- [x] Rename the title to "Weekly Report - 22"
- [x] Sort the issues / project and/or module and status
- [x] Display the status using colors and not using black text - `[closed]`

**Comment by cmoulliard** [comment]
> * Display the status using colors and not using black text - `[closed]`

Can you mark th checkoc then ;-) Next time we will create an issue / request. Sorry

**Comment by jacobdotcosta** [comment]
It seems the way github deals with colors is slightly different from what is implemented.
Check https://github.github.com/gfm/

**Comment by cmoulliard** [comment]
> It seems the way github deals with colors is slightly different from what is implemented.
> Check https://github.github.com/gfm/

What do you suggest to do then ? @jacobdotcosta

**Comment by jacobdotcosta** [comment]
I'll do it the GitHub way.

**Comment by jacobdotcosta** [comment]
From [this 6 year old thread](https://github.com/github/markup/issues/369) and the angry people comments being added until today. it seems that coloring is no longer rendered by GitHub. [These instructions](https://github.github.com/gfm/) result in showing html code.

I have implemented the workaround comented in [*How to add color to Github's README.md file* stackoverflow question](https://stackoverflow.com/questions/11509830/how-to-add-color-to-githubs-readme-md-file).

-----------------------------------------

- area/smallrye                                                                                                                                                                                                    
  -  ![#a9a9a9](https://via.placeholder.com/15/a9a9a9/000000?text=+) [`closed`] Use smallrye config's newOptionalConverter when it lands - [https://github.com/quarkusio/quarkus/issues/4166](https://github.com/quarkusio/quarkus/issues/4166)                                                                                                                                                                                       
- kind/bug                                                                                                                                                                                                         
  -  ![#ffaa00](https://via.placeholder.com/15/ffaa00/000000?text=+) [`open`] Add @Patch support for RestClient - [https://github.com/quarkusio/quarkus/issues/9342](https://github.com/quarkusio/quarkus/issues/9342)                                                                                                                                                                                                                
- 7 - Community development                                                                                                                                                                                        
  -  ![#00ff00](https://via.placeholder.com/15/00ff00/000000?text=+) [`open`] Project / Spring on Quarkus / Research BuildPacks - [https://github.com/snowdrop/team/issues/87](https://github.com/snowdrop/team/issues/87)                                                                                                                                                                                                            

--------------------------------

<style
  type="text/css">
h1 {color:red;}

p {color:blue;}
</style>
<p>okay</p>

<style>p{color:red;}</style>
<p><em>foo</em></p>
