### ISSUE TITLE
Create sb-2.7.x branch for the examples

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#880]
- [x] configmap-example
- [x] crud-example
- [x] health-check-example
- [x] istio-distributed-tracing-example
- [x] rest-http-example
