### ISSUE TITLE
Bump examples to SB 2.7.2

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#881]
- [x] configmap-example
- [x] crud-example
- [x] health-check-example
- [x] istio-distributed-tracing-example
- [x] rest-http-example

**Comment by jacobdotcosta** [comment]
CRUD example: https://github.com/snowdrop/crud-example/pull/101

**Comment by jacobdotcosta** [comment]
Config Map example: https://github.com/snowdrop/configmap-example/pull/106

**Comment by jacobdotcosta** [comment]
Health Check example: https://github.com/snowdrop/health-check-example/pull/82

**Comment by jacobdotcosta** [comment]
REST HTTP example: https://github.com/snowdrop/rest-http-example/pull/147

**Comment by jacobdotcosta** [comment]
Regarding the istio distributed tracing, I proposed adapting it to open telemetry before this next release so we stop using opentracing which we stopped updating the release almost 2 years ago. #882
