### ISSUE TITLE
SB 2.7.2 ER release

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#885]
- [x] Create JIRA release Ticket
- [x] Update Narayana Spring Boot Starter upstream
- [x] Check test results
- [x] Upstream Release
  - [x] Release Narayana Spring Boot Starter upstream
- [x] Update examples
  - [x] Dekorate
  - [x] Other GAV 
  - [x] Test examples
- [ ] Productize BOM
  - [x] Update the build configuration
  - [x] Update the CPaaS information
  - [x] Create MR
  - [x] Launch the build
  - [x] Test the release
- [x] Release examples
- [x] Inform QE

**Comment by jacobdotcosta** [comment]
Updating CPaaS structure to the new release.
