### ISSUE TITLE
SB 2.7.2 DR release

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#896]
- [x] Update Narayana Spring Boot Starter upstream
- [x] Upstream Release
  - [x] Release Narayana Spring Boot Starter upstream
- [x] Productize BOM DR in test mode
  - [x] Update the build configuration
  - [x] Execute `bacon pig run`
- [x] Execute Marete tests

**Comment by jacobdotcosta** [comment]
Fixing duplicate version errors in merete tests.
