### ISSUE TITLE
fix DR1 issues

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#947]
- duplicates
  - [ ]  jakarta.activation:jakarta.activation-api ["1.2.1.redhat-00002", "1.2.2.redhat-00001"]
  - [ ]  org.apache:apache ["23.0.0.redhat-00001", "24.0.0.redhat-00001"]
  - [ ]  com.sun.activation:all ["1.2.1.redhat-00002", "1.2.2.redhat-00001"]
- [x] missing manifests
- [x] missing GAV
- [x] Beta versions

**Comment by jacobdotcosta** [comment]
**missing manifests** fix with Dekorate `2.11.4`

**Comment by jacobdotcosta** [comment]
Wont fix the duplicates as they are internal to the `jakarta.xml.bind:jakarta.xml.bind-api:2.3.3.redhat-00001` GAV.
