### ISSUE TITLE
Remove hardcoded maven settings from run_tests_with_s2i.sh

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#956]
[ref: ENTSBT-1255](https://issues.redhat.com/browse/ENTSBT-1255)

- [x] configmap-example - https://github.com/snowdrop/configmap-example/pull/115
- [x] crud-example - https://github.com/snowdrop/crud-example/pull/118
- [x] health-check-example - https://github.com/snowdrop/health-check-example/pull/91
- [x] rest-http-example - https://github.com/snowdrop/rest-http-example/pull/160
