### ISSUE TITLE
fix: examples - no matches for kind "Template" in version "v1"

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#960]
ref: ENTSBT-1254
- [x] configmap-example - snowdrop/configmap-example#116
- [x]  crud-example - snowdrop/crud-example#119
- [x]  health-check-example - snowdrop/health-check-example#92
- [x]  rest-http-example - snowdrop/rest-http-example#162
