### ISSUE TITLE
S2I shell script does not pass template parameter MAVEN_MIRROR_URL

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#966]
[ref: ENTSBT-1260](https://issues.redhat.com/browse/ENTSBT-1260)

- [x] configmap-example - https://github.com/snowdrop/configmap-example/pull/117
- [x] crud-example - https://github.com/snowdrop/crud-example/pull/124
- [x] health-check-example - https://github.com/snowdrop/health-check-example/pull/93
- [x] rest-http-example - https://github.com/snowdrop/rest-http-example/pull/163
