### ISSUE TITLE
Release SB 2.7.8 ER

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#997]
- [x] ~Update build configuration~
- [x] CPaaS Setup
  - [x] Check CPaaS version
  - [x] Update CPaaS configuration
- [ ] ~Launch ER build~
- [x] Release examples
- [x] Update `artifact-list` file
- [x] Errata Advisory
